# Generated by Django 4.2 on 2024-08-11 17:51

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_price_alter_assignment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.get_upload_to_assignments),
        ),
    ]
