# Generated by Django 4.2 on 2024-08-31 12:56

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_assignment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.get_upload_to_submissions),
        ),
    ]
